### ISSUE TITLE
Your callbacks seem to not be working. Can you please publish a demo of working callbacks

### ISSUE THREAD

**Issue by matthewnewman43** [ersurajnegi/ngx-malihu-scroller#1]

**Comment by ersurajnegi** [comment]
@matthewnewman43 .. it is working for me. you can check it out on 
https://ersurajnegi.github.io/ngxMalihuScrollerDemo/test1 . scroll on any scroller and check console logs, event is getting fired.
Could you please share your repo, i can check it out once.
Thanks for using this. :-)
Below is my code for your reference:
![image](https://user-images.githubusercontent.com/16935216/34165513-80e103ba-e502-11e7-839e-c6bd33310532.png)

![image](https://user-images.githubusercontent.com/16935216/34165449-54048eb6-e502-11e7-9525-280ec3db5fa2.png)

**Comment by ersurajnegi** [comment]
Closing the issue.
